import { useState } from "react";
import { Film, X } from "lucide-react";
import type { MatchResult } from "../lib/api";
import type { useT } from "../i18n";
import "./MatchPanel.css";

export default function MatchResultView({ result, onClose, t }: { result: MatchResult; onClose: () => void; t: ReturnType<typeof useT> }) {
  const [expanded, setExpanded] = useState<string | null>(null);
  const groups = ["ct", "t"] as const;
  return <div className="match-page match-results"><header className="workspace__head match-page__head"><div><span className="workspace__eyebrow">{t("match.resultsEyebrow")}</span><h1>{t("match.results")}</h1><p>{result.map_id.toUpperCase()} · {result.opponent_name} · {result.state}</p></div><button className="match-history-button" onClick={onClose}><X size={16} />{t("match.backToLobby")}</button></header><div className="match-scoreline glass"><div><span>{t("match.yourTeam")}</span><strong>{result.player_score}</strong></div><div className="match-scoreline__center"><span>{result.state === "finished" ? t("match.finished") : t("match.interrupted")}</span><small>{result.rating_model_version}</small></div><div><span>{result.opponent_name}</span><strong>{result.opponent_score}</strong></div></div><div className="match-result-table glass"><div className="match-result-header"><span>{t("match.player")}</span><span>K-D</span><span>ADR</span><span>KAST</span><span>HS%</span><span>{t("match.swing")}</span><span>Rating Plus</span></div>{groups.map((group) => <div key={group}><div className="match-team-divider"><span>{group === "ct" ? "CT" : "T"}</span><small>{result.players.filter((player) => player.team === group).length} {t("match.players")}</small></div>{result.players.filter((player) => player.team === group).sort((a, b) => (b.rating?.rating_plus ?? 0) - (a.rating?.rating_plus ?? 0)).map((player) => <div className="match-result-row" key={player.player_id} onClick={() => setExpanded(expanded === player.player_id ? null : player.player_id)}><span className="match-player-name"><span className={`match-kind kind-${player.kind}`}>{player.kind === "human" ? "P" : "B"}</span><strong>{player.name}</strong></span><span className={player.difference >= 0 ? "positive" : "negative"}>{player.kills}-{player.deaths}</span><span>{player.adr.toFixed(1)}</span><span>{player.kast_percent.toFixed(0)}%</span><span>{player.headshot_percent.toFixed(0)}%</span><span>{player.round_swing.toFixed(2)}</span><strong className="rating-plus">{player.rating?.rating_plus.toFixed(2) ?? "--"}</strong>{expanded === player.player_id && <div className="match-player-detail"><span>Kills {player.rating?.kills.toFixed(2) ?? "--"}</span><span>Damage {player.rating?.damage.toFixed(2) ?? "--"}</span><span>Survival {player.rating?.survival.toFixed(2) ?? "--"}</span><span>KAST {player.rating?.kast.toFixed(2) ?? "--"}</span><span>Multi {player.rating?.multi_kills.toFixed(2) ?? "--"}</span><span>Round Swing {player.rating?.round_swing.toFixed(2) ?? "--"}</span><span>Economy {player.rating?.economy_adjustment.toFixed(2) ?? "--"}</span></div>}</div>)}</div>)}</div><div className="match-demo-banner"><Film size={16} /><span>{t("match.demoStatus")}: <strong>{result.demo.state}</strong>{result.demo.path && <small>{result.demo.path}</small>}</span></div></div>;
}
